import '#define/dial.ts';
import '#define/envelope.ts';
import '#define/button.ts';
import '#define/switch.ts';
import '#define/meter.ts';
import '#define/number.ts';
import '#define/segmented.ts';
import '#define/slider.ts';
import '#define/split.ts';
import '#define/waveform.ts';
import '#define/wavestrip.ts';
import '#define/xy.ts';

export type { SonicButton } from '#define/button.ts';
export type { SonicDial } from '#define/dial.ts';
export type { SonicEnvelope } from '#define/envelope.ts';
export type { SonicMeter } from '#define/meter.ts';
export type { SonicNumber } from '#define/number.ts';
export type { SonicSegmented } from '#define/segmented.ts';
export type { SonicSlider } from '#define/slider.ts';
export type { SonicSplit } from '#define/split.ts';
export type { SonicSwitch } from '#define/switch.ts';
export type { SonicWaveform } from '#define/waveform.ts';
export type { SonicWavestrip } from '#define/wavestrip.ts';
export type { SonicXy } from '#define/xy.ts';
