import '#define/dial.ts';
import '#define/envelope.ts';
import '#define/key.ts';
import '#define/lever.ts';
import '#define/meter.ts';
import '#define/number.ts';
import '#define/segmented.ts';
import '#define/slider.ts';
import '#define/sum.ts';
import '#define/waveform.ts';
import '#define/wavestrip.ts';
import '#define/xy.ts';

export type { SonicDial } from '#define/dial.ts';
export type { SonicEnvelope } from '#define/envelope.ts';
export type { SonicKey } from '#define/key.ts';
export type { SonicLever } from '#define/lever.ts';
export type { SonicMeter } from '#define/meter.ts';
export type { SonicNumber } from '#define/number.ts';
export type { SonicSegmented } from '#define/segmented.ts';
export type { SonicSlider } from '#define/slider.ts';
export type { SonicSum } from '#define/sum.ts';
export type { SonicWaveform } from '#define/waveform.ts';
export type { SonicWavestrip } from '#define/wavestrip.ts';
export type { SonicXy } from '#define/xy.ts';
